* Client Commands

** join Seamus green 
This requests joining a game. Server returns "joined" command and
lists other players, their colors, their positions.

** move row,col
row is an integer [1,19] and col is a letter [A,S].

* Server Commands

** joined seamus:green:4 bossy:brown:1 Steven:blue:2 Bart:purple:3
This is returned to a player, when they successfully join a game. They
are returned their position, and also the other players.

** update <Matrix_map> lastmove:3,1,D  capture:3,1 capture:3,2
This is sent to each player after each player move. It returns the
updated grid, the move, and any captures taken during the move.

** turn 3
This is sent to each player after each player turn change.

** illegal_move <reason>
This is sent to a player when they make an illegal move. They must
reply with a different move. Reason can be 
*** "no such intersection" 
intersection selected out of bounds.
*** "intersection occupied"
intersection is already occupied.
*** "incorrect form"
move was not in the form "row,col"

** game_won <player_pos> reason:sequence sequence:1,A;2,B;3,C;4,D;5,E 
The game won message is sent to all players, when a player wins the
game. It includes which player won, how they won (sequence or
captures), the sequence (or null if no sequence). If its a sequence
win it sends the sequence, so a client can outline the sequence on the
grid.

** player_resign <player_pos>
If a player resigns, they are logged out and the players are notifed. 
*** What happens to resigned players stones
Perhaps they are left on the board for other players to continue
capturing and the pairs that the other players captured are also left
in the game.  

